Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/11/2021
Var
// Seção de Declarações das variáveis 

    a: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a<-1
repita
escreval(a)
ate a<10
Fimalgoritmo